#!/bin/bash

echo "Cleaning and building"
# Just a script to compile th tools
cd tools/bitset/ && make clean && make && cd ..
cd client/ && make clean && make && cd ..
cd mk8900image/ && make clean && make && cd ..
cd img3decrypt/ && make clean && make && cd ..

echo "Installing to ../bin"
# Now copy the binaries into the bin directory
rm -f ../bin/mk8900image && cp mk8900image/mk8900image ../bin/mk8900image
rm -f ../bin/loadibec && cp client/loadibec ../bin/loadibec
rm -f ../bin/oibc && cp client/oibc ../bin/oibc
rm -f ../bin/linux && cp client/linux ../bin/linux
rm -f ../bin/bitset && cp bitset/bitset ../bin/bitset
rm -f ../bin/img3decrypt && cp img3decrypt/img3decrypt ../bin/img3decrypt

echo "Cleaning up."
cd bitset/ && make clean && cd ..
cd client/ && make clean && cd ..
cd img3decrypt/ && make clean && cd ..
cd mk8900image/ && make clean && cd ../..
echo "Done."
